// Ported from microsoft/microsoft-ui-reactor @7c90d29 (tests/Reactor.Tests/YogaGenerated/YogaAndroidNewsFeed.cs).
// Upstream licence: MIT (Microsoft Corporation). Original fixtures: Meta's Yoga (MIT).

using Comet.Layout.Yoga;
using Comet.Layout.Yoga;
using Xunit;

namespace Comet.Layout.Yoga.Tests.YogaGenerated;

/// <summary>
/// Ported from yoga/tests/generated/YGAndroidNewsFeed.cpp
/// </summary>
public class YogaAndroidNewsFeed
{
    [Fact]
    public void Android_News_Feed()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.AlignContent = FlexAlign.Stretch;
        root.Width = YogaValue.Point(1080f);
        var root_child0 = new YogaNode(config);
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        var root_child0_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child0_child0.AlignItems = FlexAlign.FlexStart;
        root_child0_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0.SetMargin(YogaEdge.Top, YogaValue.Point(24f));
        root_child0_child0_child0_child0.SetMargin(YogaEdge.Start, YogaValue.Point(36f));
        root_child0_child0_child0.InsertChild(root_child0_child0_child0_child0, 0);
        var root_child0_child0_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0_child0_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0.InsertChild(root_child0_child0_child0_child0_child0, 0);
        var root_child0_child0_child0_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0_child0_child0.Width = YogaValue.Point(120f);
        root_child0_child0_child0_child0_child0_child0.Height = YogaValue.Point(120f);
        root_child0_child0_child0_child0_child0.InsertChild(root_child0_child0_child0_child0_child0_child0, 0);
        var root_child0_child0_child0_child0_child1 = new YogaNode(config);
        root_child0_child0_child0_child0_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0_child1.FlexShrink = 1f;
        root_child0_child0_child0_child0_child1.SetMargin(YogaEdge.Right, YogaValue.Point(36f));
        root_child0_child0_child0_child0_child1.SetPadding(YogaEdge.Left, YogaValue.Point(36f));
        root_child0_child0_child0_child0_child1.SetPadding(YogaEdge.Top, YogaValue.Point(21f));
        root_child0_child0_child0_child0_child1.SetPadding(YogaEdge.Right, YogaValue.Point(36f));
        root_child0_child0_child0_child0_child1.SetPadding(YogaEdge.Bottom, YogaValue.Point(18f));
        root_child0_child0_child0_child0.InsertChild(root_child0_child0_child0_child0_child1, 1);
        var root_child0_child0_child0_child0_child1_child0 = new YogaNode(config);
        root_child0_child0_child0_child0_child1_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child0_child0_child1_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0_child1_child0.FlexShrink = 1f;
        root_child0_child0_child0_child0_child1.InsertChild(root_child0_child0_child0_child0_child1_child0, 0);
        var root_child0_child0_child0_child0_child1_child1 = new YogaNode(config);
        root_child0_child0_child0_child0_child1_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0_child1_child1.FlexShrink = 1f;
        root_child0_child0_child0_child0_child1.InsertChild(root_child0_child0_child0_child0_child1_child1, 1);
        var root_child0_child0_child1 = new YogaNode(config);
        root_child0_child0_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0.InsertChild(root_child0_child0_child1, 1);
        var root_child0_child0_child1_child0 = new YogaNode(config);
        root_child0_child0_child1_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child1_child0.AlignItems = FlexAlign.FlexStart;
        root_child0_child0_child1_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0.SetMargin(YogaEdge.Top, YogaValue.Point(24f));
        root_child0_child0_child1_child0.SetMargin(YogaEdge.Start, YogaValue.Point(174f));
        root_child0_child0_child1.InsertChild(root_child0_child0_child1_child0, 0);
        var root_child0_child0_child1_child0_child0 = new YogaNode(config);
        root_child0_child0_child1_child0_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child1_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0.InsertChild(root_child0_child0_child1_child0_child0, 0);
        var root_child0_child0_child1_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child1_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0_child0_child0.Width = YogaValue.Point(72f);
        root_child0_child0_child1_child0_child0_child0.Height = YogaValue.Point(72f);
        root_child0_child0_child1_child0_child0.InsertChild(root_child0_child0_child1_child0_child0_child0, 0);
        var root_child0_child0_child1_child0_child1 = new YogaNode(config);
        root_child0_child0_child1_child0_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0_child1.FlexShrink = 1f;
        root_child0_child0_child1_child0_child1.SetMargin(YogaEdge.Right, YogaValue.Point(36f));
        root_child0_child0_child1_child0_child1.SetPadding(YogaEdge.Left, YogaValue.Point(36f));
        root_child0_child0_child1_child0_child1.SetPadding(YogaEdge.Top, YogaValue.Point(21f));
        root_child0_child0_child1_child0_child1.SetPadding(YogaEdge.Right, YogaValue.Point(36f));
        root_child0_child0_child1_child0_child1.SetPadding(YogaEdge.Bottom, YogaValue.Point(18f));
        root_child0_child0_child1_child0.InsertChild(root_child0_child0_child1_child0_child1, 1);
        var root_child0_child0_child1_child0_child1_child0 = new YogaNode(config);
        root_child0_child0_child1_child0_child1_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child1_child0_child1_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0_child1_child0.FlexShrink = 1f;
        root_child0_child0_child1_child0_child1.InsertChild(root_child0_child0_child1_child0_child1_child0, 0);
        var root_child0_child0_child1_child0_child1_child1 = new YogaNode(config);
        root_child0_child0_child1_child0_child1_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0_child1_child1.FlexShrink = 1f;
        root_child0_child0_child1_child0_child1.InsertChild(root_child0_child0_child1_child0_child1_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(1080f, root.LayoutWidth);
        Assert.Equal(240f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(1080f, root_child0.LayoutWidth);
        Assert.Equal(240f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(1080f, root_child0_child0.LayoutWidth);
        Assert.Equal(240f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(1080f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(144f, root_child0_child0_child0.LayoutHeight);
        Assert.Equal(36f, root_child0_child0_child0_child0.LayoutX);
        Assert.Equal(24f, root_child0_child0_child0_child0.LayoutY);
        Assert.Equal(1044f, root_child0_child0_child0_child0.LayoutWidth);
        Assert.Equal(120f, root_child0_child0_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0_child0_child0.LayoutY);
        Assert.Equal(120f, root_child0_child0_child0_child0_child0.LayoutWidth);
        Assert.Equal(120f, root_child0_child0_child0_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0_child0_child0_child0.LayoutY);
        Assert.Equal(120f, root_child0_child0_child0_child0_child0_child0.LayoutWidth);
        Assert.Equal(120f, root_child0_child0_child0_child0_child0_child0.LayoutHeight);
        Assert.Equal(120f, root_child0_child0_child0_child0_child1.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1.LayoutY);
        Assert.Equal(72f, root_child0_child0_child0_child0_child1.LayoutWidth);
        Assert.Equal(39f, root_child0_child0_child0_child0_child1.LayoutHeight);
        Assert.Equal(36f, root_child0_child0_child0_child0_child1_child0.LayoutX);
        Assert.Equal(21f, root_child0_child0_child0_child0_child1_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1_child0.LayoutHeight);
        Assert.Equal(36f, root_child0_child0_child0_child0_child1_child1.LayoutX);
        Assert.Equal(21f, root_child0_child0_child0_child0_child1_child1.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1_child1.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1_child1.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child1.LayoutX);
        Assert.Equal(144f, root_child0_child0_child1.LayoutY);
        Assert.Equal(1080f, root_child0_child0_child1.LayoutWidth);
        Assert.Equal(96f, root_child0_child0_child1.LayoutHeight);
        Assert.Equal(174f, root_child0_child0_child1_child0.LayoutX);
        Assert.Equal(24f, root_child0_child0_child1_child0.LayoutY);
        Assert.Equal(906f, root_child0_child0_child1_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child1_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child1_child0_child0.LayoutY);
        Assert.Equal(72f, root_child0_child0_child1_child0_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0_child1_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child1_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child1_child0_child0_child0.LayoutY);
        Assert.Equal(72f, root_child0_child0_child1_child0_child0_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0_child1_child0_child0_child0.LayoutHeight);
        Assert.Equal(72f, root_child0_child0_child1_child0_child1.LayoutX);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1.LayoutY);
        Assert.Equal(72f, root_child0_child0_child1_child0_child1.LayoutWidth);
        Assert.Equal(39f, root_child0_child0_child1_child0_child1.LayoutHeight);
        Assert.Equal(36f, root_child0_child0_child1_child0_child1_child0.LayoutX);
        Assert.Equal(21f, root_child0_child0_child1_child0_child1_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1_child0.LayoutHeight);
        Assert.Equal(36f, root_child0_child0_child1_child0_child1_child1.LayoutX);
        Assert.Equal(21f, root_child0_child0_child1_child0_child1_child1.LayoutY);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1_child1.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(1080f, root.LayoutWidth);
        Assert.Equal(240f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(1080f, root_child0.LayoutWidth);
        Assert.Equal(240f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(1080f, root_child0_child0.LayoutWidth);
        Assert.Equal(240f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(1080f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(144f, root_child0_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0_child0.LayoutX);
        Assert.Equal(24f, root_child0_child0_child0_child0.LayoutY);
        Assert.Equal(1044f, root_child0_child0_child0_child0.LayoutWidth);
        Assert.Equal(120f, root_child0_child0_child0_child0.LayoutHeight);
        Assert.Equal(924f, root_child0_child0_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0_child0_child0.LayoutY);
        Assert.Equal(120f, root_child0_child0_child0_child0_child0.LayoutWidth);
        Assert.Equal(120f, root_child0_child0_child0_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0_child0_child0_child0.LayoutY);
        Assert.Equal(120f, root_child0_child0_child0_child0_child0_child0.LayoutWidth);
        Assert.Equal(120f, root_child0_child0_child0_child0_child0_child0.LayoutHeight);
        Assert.Equal(816f, root_child0_child0_child0_child0_child1.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1.LayoutY);
        Assert.Equal(72f, root_child0_child0_child0_child0_child1.LayoutWidth);
        Assert.Equal(39f, root_child0_child0_child0_child0_child1.LayoutHeight);
        Assert.Equal(36f, root_child0_child0_child0_child0_child1_child0.LayoutX);
        Assert.Equal(21f, root_child0_child0_child0_child0_child1_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1_child0.LayoutHeight);
        Assert.Equal(36f, root_child0_child0_child0_child0_child1_child1.LayoutX);
        Assert.Equal(21f, root_child0_child0_child0_child0_child1_child1.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1_child1.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0_child0_child1_child1.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child1.LayoutX);
        Assert.Equal(144f, root_child0_child0_child1.LayoutY);
        Assert.Equal(1080f, root_child0_child0_child1.LayoutWidth);
        Assert.Equal(96f, root_child0_child0_child1.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child1_child0.LayoutX);
        Assert.Equal(24f, root_child0_child0_child1_child0.LayoutY);
        Assert.Equal(906f, root_child0_child0_child1_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0_child1_child0.LayoutHeight);
        Assert.Equal(834f, root_child0_child0_child1_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child1_child0_child0.LayoutY);
        Assert.Equal(72f, root_child0_child0_child1_child0_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0_child1_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child1_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child1_child0_child0_child0.LayoutY);
        Assert.Equal(72f, root_child0_child0_child1_child0_child0_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0_child1_child0_child0_child0.LayoutHeight);
        Assert.Equal(726f, root_child0_child0_child1_child0_child1.LayoutX);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1.LayoutY);
        Assert.Equal(72f, root_child0_child0_child1_child0_child1.LayoutWidth);
        Assert.Equal(39f, root_child0_child0_child1_child0_child1.LayoutHeight);
        Assert.Equal(36f, root_child0_child0_child1_child0_child1_child0.LayoutX);
        Assert.Equal(21f, root_child0_child0_child1_child0_child1_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1_child0.LayoutHeight);
        Assert.Equal(36f, root_child0_child0_child1_child0_child1_child1.LayoutX);
        Assert.Equal(21f, root_child0_child0_child1_child0_child1_child1.LayoutY);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1_child1.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child1_child0_child1_child1.LayoutHeight);
    }

}