// Ported from microsoft/microsoft-ui-reactor @7c90d29 (tests/Reactor.Tests/YogaGenerated/YogaRoundingTest.cs).
// Upstream licence: MIT (Microsoft Corporation). Original fixtures: Meta's Yoga (MIT).

using Comet.Layout.Yoga;
using Comet.Layout.Yoga;
using Xunit;

namespace Comet.Layout.Yoga.Tests.YogaGenerated;

/// <summary>
/// Ported from yoga/tests/generated/YGRoundingTest.cpp
/// </summary>
public class YogaRoundingTest
{
    [Fact]
    public void Rounding_Flex_Basis_Flex_Grow_Row_Width_Of_100()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(33f, root_child0.LayoutWidth);
        Assert.Equal(100f, root_child0.LayoutHeight);
        Assert.Equal(33f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(34f, root_child1.LayoutWidth);
        Assert.Equal(100f, root_child1.LayoutHeight);
        Assert.Equal(67f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(33f, root_child2.LayoutWidth);
        Assert.Equal(100f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(67f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(33f, root_child0.LayoutWidth);
        Assert.Equal(100f, root_child0.LayoutHeight);
        Assert.Equal(33f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(34f, root_child1.LayoutWidth);
        Assert.Equal(100f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(33f, root_child2.LayoutWidth);
        Assert.Equal(100f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Flex_Basis_Flex_Grow_Row_Prime_Number_Width()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(113f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.FlexGrow = 1f;
        root.InsertChild(root_child3, 3);
        var root_child4 = new YogaNode(config);
        root_child4.FlexGrow = 1f;
        root.InsertChild(root_child4, 4);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(113f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(23f, root_child0.LayoutWidth);
        Assert.Equal(100f, root_child0.LayoutHeight);
        Assert.Equal(23f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(22f, root_child1.LayoutWidth);
        Assert.Equal(100f, root_child1.LayoutHeight);
        Assert.Equal(45f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(23f, root_child2.LayoutWidth);
        Assert.Equal(100f, root_child2.LayoutHeight);
        Assert.Equal(68f, root_child3.LayoutX);
        Assert.Equal(0f, root_child3.LayoutY);
        Assert.Equal(22f, root_child3.LayoutWidth);
        Assert.Equal(100f, root_child3.LayoutHeight);
        Assert.Equal(90f, root_child4.LayoutX);
        Assert.Equal(0f, root_child4.LayoutY);
        Assert.Equal(23f, root_child4.LayoutWidth);
        Assert.Equal(100f, root_child4.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(113f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(90f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(23f, root_child0.LayoutWidth);
        Assert.Equal(100f, root_child0.LayoutHeight);
        Assert.Equal(68f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(22f, root_child1.LayoutWidth);
        Assert.Equal(100f, root_child1.LayoutHeight);
        Assert.Equal(45f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(23f, root_child2.LayoutWidth);
        Assert.Equal(100f, root_child2.LayoutHeight);
        Assert.Equal(23f, root_child3.LayoutX);
        Assert.Equal(0f, root_child3.LayoutY);
        Assert.Equal(22f, root_child3.LayoutWidth);
        Assert.Equal(100f, root_child3.LayoutHeight);
        Assert.Equal(0f, root_child4.LayoutX);
        Assert.Equal(0f, root_child4.LayoutY);
        Assert.Equal(23f, root_child4.LayoutWidth);
        Assert.Equal(100f, root_child4.LayoutHeight);
    }

    [Fact]
    public void Rounding_Flex_Basis_Flex_Shrink_Row()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(101f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.FlexBasis = YogaValue.Point(100f);
        root_child0.FlexShrink = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.FlexBasis = YogaValue.Point(25f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.FlexBasis = YogaValue.Point(25f);
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(101f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(51f, root_child0.LayoutWidth);
        Assert.Equal(100f, root_child0.LayoutHeight);
        Assert.Equal(51f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(25f, root_child1.LayoutWidth);
        Assert.Equal(100f, root_child1.LayoutHeight);
        Assert.Equal(76f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(25f, root_child2.LayoutWidth);
        Assert.Equal(100f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(101f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(51f, root_child0.LayoutWidth);
        Assert.Equal(100f, root_child0.LayoutHeight);
        Assert.Equal(25f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(25f, root_child1.LayoutWidth);
        Assert.Equal(100f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(25f, root_child2.LayoutWidth);
        Assert.Equal(100f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Flex_Basis_Overrides_Main_Size()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(64f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(64f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(64f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(64f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Total_Fractial()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(87.4f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20.3f);
        root_child0.FlexGrow = 0.7f;
        root_child0.FlexBasis = YogaValue.Point(50.3f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1.6f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10.7f);
        root_child2.FlexGrow = 1.1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(87f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(87f, root_child0.LayoutWidth);
        Assert.Equal(59f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(59f, root_child1.LayoutY);
        Assert.Equal(87f, root_child1.LayoutWidth);
        Assert.Equal(30f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(87f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(87f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(87f, root_child0.LayoutWidth);
        Assert.Equal(59f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(59f, root_child1.LayoutY);
        Assert.Equal(87f, root_child1.LayoutWidth);
        Assert.Equal(30f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(87f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Total_Fractial_Nested()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(87.4f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20.3f);
        root_child0.FlexGrow = 0.7f;
        root_child0.FlexBasis = YogaValue.Point(50.3f);
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.SetPosition(YogaEdge.Bottom, YogaValue.Point(13.3f));
        root_child0_child0.Height = YogaValue.Point(9.9f);
        root_child0_child0.FlexGrow = 1f;
        root_child0_child0.FlexBasis = YogaValue.Point(0.3f);
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child1 = new YogaNode(config);
        root_child0_child1.SetPosition(YogaEdge.Top, YogaValue.Point(13.3f));
        root_child0_child1.Height = YogaValue.Point(1.1f);
        root_child0_child1.FlexGrow = 4f;
        root_child0_child1.FlexBasis = YogaValue.Point(0.3f);
        root_child0.InsertChild(root_child0_child1, 1);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1.6f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10.7f);
        root_child2.FlexGrow = 1.1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(87f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(87f, root_child0.LayoutWidth);
        Assert.Equal(59f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(-13f, root_child0_child0.LayoutY);
        Assert.Equal(87f, root_child0_child0.LayoutWidth);
        Assert.Equal(12f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child1.LayoutX);
        Assert.Equal(25f, root_child0_child1.LayoutY);
        Assert.Equal(87f, root_child0_child1.LayoutWidth);
        Assert.Equal(47f, root_child0_child1.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(59f, root_child1.LayoutY);
        Assert.Equal(87f, root_child1.LayoutWidth);
        Assert.Equal(30f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(87f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(87f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(87f, root_child0.LayoutWidth);
        Assert.Equal(59f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(-13f, root_child0_child0.LayoutY);
        Assert.Equal(87f, root_child0_child0.LayoutWidth);
        Assert.Equal(12f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child1.LayoutX);
        Assert.Equal(25f, root_child0_child1.LayoutY);
        Assert.Equal(87f, root_child0_child1.LayoutWidth);
        Assert.Equal(47f, root_child0_child1.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(59f, root_child1.LayoutY);
        Assert.Equal(87f, root_child1.LayoutWidth);
        Assert.Equal(30f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(87f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Fractial_Input_1()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(64f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(64f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(64f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(64f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Fractial_Input_2()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113.6f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(114f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(65f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(65f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(24f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(25f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(114f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(65f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(65f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(24f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(25f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Fractial_Input_3()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.SetPosition(YogaEdge.Top, YogaValue.Point(0.3f));
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(114f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(65f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(64f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(24f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(25f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(114f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(65f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(64f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(24f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(25f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Fractial_Input_4()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.SetPosition(YogaEdge.Top, YogaValue.Point(0.7f));
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(1f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(64f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(64f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(1f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(113f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(64f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(64f, root_child1.LayoutY);
        Assert.Equal(100f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(89f, root_child2.LayoutY);
        Assert.Equal(100f, root_child2.LayoutWidth);
        Assert.Equal(24f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Inner_Node_Controversy_Horizontal()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(320f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Height = YogaValue.Point(10f);
        root_child1_child0.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(320f, root.LayoutWidth);
        Assert.Equal(10f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(107f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
        Assert.Equal(107f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(106f, root_child1.LayoutWidth);
        Assert.Equal(10f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(106f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        Assert.Equal(213f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(107f, root_child2.LayoutWidth);
        Assert.Equal(10f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(320f, root.LayoutWidth);
        Assert.Equal(10f, root.LayoutHeight);
        Assert.Equal(213f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(107f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
        Assert.Equal(107f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(106f, root_child1.LayoutWidth);
        Assert.Equal(10f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(106f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(107f, root_child2.LayoutWidth);
        Assert.Equal(10f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Inner_Node_Controversy_Vertical()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(320f);
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(10f);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(10f);
        root_child1_child0.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child2 = new YogaNode(config);
        root_child2.Width = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(10f, root.LayoutWidth);
        Assert.Equal(320f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(10f, root_child0.LayoutWidth);
        Assert.Equal(107f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(107f, root_child1.LayoutY);
        Assert.Equal(10f, root_child1.LayoutWidth);
        Assert.Equal(106f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(10f, root_child1_child0.LayoutWidth);
        Assert.Equal(106f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(213f, root_child2.LayoutY);
        Assert.Equal(10f, root_child2.LayoutWidth);
        Assert.Equal(107f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(10f, root.LayoutWidth);
        Assert.Equal(320f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(10f, root_child0.LayoutWidth);
        Assert.Equal(107f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(107f, root_child1.LayoutY);
        Assert.Equal(10f, root_child1.LayoutWidth);
        Assert.Equal(106f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(10f, root_child1_child0.LayoutWidth);
        Assert.Equal(106f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(213f, root_child2.LayoutY);
        Assert.Equal(10f, root_child2.LayoutWidth);
        Assert.Equal(107f, root_child2.LayoutHeight);
    }

    [Fact]
    public void Rounding_Inner_Node_Controversy_Combined()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(640f);
        root.Height = YogaValue.Point(320f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Percent(100f);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Percent(100f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Percent(100f);
        root_child1_child0.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child1_child1 = new YogaNode(config);
        root_child1_child1.Width = YogaValue.Percent(100f);
        root_child1_child1.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child1, 1);
        var root_child1_child1_child0 = new YogaNode(config);
        root_child1_child1_child0.FlexGrow = 1f;
        root_child1_child1_child0.Width = YogaValue.Percent(100f);
        root_child1_child1.InsertChild(root_child1_child1_child0, 0);
        var root_child1_child2 = new YogaNode(config);
        root_child1_child2.Width = YogaValue.Percent(100f);
        root_child1_child2.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child2, 2);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Percent(100f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(640f, root.LayoutWidth);
        Assert.Equal(320f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(213f, root_child0.LayoutWidth);
        Assert.Equal(320f, root_child0.LayoutHeight);
        Assert.Equal(213f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(214f, root_child1.LayoutWidth);
        Assert.Equal(320f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(214f, root_child1_child0.LayoutWidth);
        Assert.Equal(107f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child1_child1.LayoutX);
        Assert.Equal(107f, root_child1_child1.LayoutY);
        Assert.Equal(214f, root_child1_child1.LayoutWidth);
        Assert.Equal(106f, root_child1_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child1_child0.LayoutY);
        Assert.Equal(214f, root_child1_child1_child0.LayoutWidth);
        Assert.Equal(106f, root_child1_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child1_child2.LayoutX);
        Assert.Equal(213f, root_child1_child2.LayoutY);
        Assert.Equal(214f, root_child1_child2.LayoutWidth);
        Assert.Equal(107f, root_child1_child2.LayoutHeight);
        Assert.Equal(427f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(213f, root_child2.LayoutWidth);
        Assert.Equal(320f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(640f, root.LayoutWidth);
        Assert.Equal(320f, root.LayoutHeight);
        Assert.Equal(427f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(213f, root_child0.LayoutWidth);
        Assert.Equal(320f, root_child0.LayoutHeight);
        Assert.Equal(213f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(214f, root_child1.LayoutWidth);
        Assert.Equal(320f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(214f, root_child1_child0.LayoutWidth);
        Assert.Equal(107f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child1_child1.LayoutX);
        Assert.Equal(107f, root_child1_child1.LayoutY);
        Assert.Equal(214f, root_child1_child1.LayoutWidth);
        Assert.Equal(106f, root_child1_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child1_child0.LayoutY);
        Assert.Equal(214f, root_child1_child1_child0.LayoutWidth);
        Assert.Equal(106f, root_child1_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child1_child2.LayoutX);
        Assert.Equal(213f, root_child1_child2.LayoutY);
        Assert.Equal(214f, root_child1_child2.LayoutWidth);
        Assert.Equal(107f, root_child1_child2.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(213f, root_child2.LayoutWidth);
        Assert.Equal(320f, root_child2.LayoutHeight);
    }

}