// Ported from microsoft/microsoft-ui-reactor @7c90d29 (tests/Reactor.Tests/YogaGenerated/YogaAlignItemsTest.cs).
// Upstream licence: MIT (Microsoft Corporation). Original fixtures: Meta's Yoga (MIT).

using Comet.Layout.Yoga;
using Comet.Layout.Yoga;
using Xunit;

namespace Comet.Layout.Yoga.Tests.YogaGenerated;

/// <summary>
/// Ported from yoga/tests/generated/YGAlignItemsTest.cpp
/// </summary>
public class FlexAlignItemsTest
{
    [Fact]
    public void Align_Items_Stretch()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root.InsertChild(root_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Items_Center()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.AlignItems = FlexAlign.Center;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(10f);
        root.InsertChild(root_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(45f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(10f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(45f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(10f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Items_Flex_Start()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.AlignItems = FlexAlign.FlexStart;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(10f);
        root.InsertChild(root_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(10f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(90f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(10f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Items_Flex_End()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.AlignItems = FlexAlign.FlexEnd;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(10f);
        root.InsertChild(root_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(90f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(10f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(10f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(20f);
        root.InsertChild(root_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(30f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(30f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Child()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(20f);
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(50f);
        root_child1_child0.Height = YogaValue.Point(10f);
        root_child1.InsertChild(root_child1_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Child_Multiline()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(60f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(25f);
        root_child1.FlexWrap = FlexWrap.Wrap;
        root_child1.FlexDirection = FlexDirection.Row;
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(25f);
        root_child1_child0.Height = YogaValue.Point(20f);
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child1_child1 = new YogaNode(config);
        root_child1_child1.Width = YogaValue.Point(25f);
        root_child1_child1.Height = YogaValue.Point(10f);
        root_child1.InsertChild(root_child1_child1, 1);
        var root_child1_child2 = new YogaNode(config);
        root_child1_child2.Width = YogaValue.Point(25f);
        root_child1_child2.Height = YogaValue.Point(20f);
        root_child1.InsertChild(root_child1_child2, 2);
        var root_child1_child3 = new YogaNode(config);
        root_child1_child3.Width = YogaValue.Point(25f);
        root_child1_child3.Height = YogaValue.Point(10f);
        root_child1.InsertChild(root_child1_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(60f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(25f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(25f, root_child1_child1.LayoutX);
        Assert.Equal(0f, root_child1_child1.LayoutY);
        Assert.Equal(25f, root_child1_child1.LayoutWidth);
        Assert.Equal(10f, root_child1_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child2.LayoutX);
        Assert.Equal(20f, root_child1_child2.LayoutY);
        Assert.Equal(25f, root_child1_child2.LayoutWidth);
        Assert.Equal(20f, root_child1_child2.LayoutHeight);
        Assert.Equal(25f, root_child1_child3.LayoutX);
        Assert.Equal(20f, root_child1_child3.LayoutY);
        Assert.Equal(25f, root_child1_child3.LayoutWidth);
        Assert.Equal(10f, root_child1_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(60f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(25f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(25f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child1_child1.LayoutX);
        Assert.Equal(0f, root_child1_child1.LayoutY);
        Assert.Equal(25f, root_child1_child1.LayoutWidth);
        Assert.Equal(10f, root_child1_child1.LayoutHeight);
        Assert.Equal(25f, root_child1_child2.LayoutX);
        Assert.Equal(20f, root_child1_child2.LayoutY);
        Assert.Equal(25f, root_child1_child2.LayoutWidth);
        Assert.Equal(20f, root_child1_child2.LayoutHeight);
        Assert.Equal(0f, root_child1_child3.LayoutX);
        Assert.Equal(20f, root_child1_child3.LayoutY);
        Assert.Equal(25f, root_child1_child3.LayoutWidth);
        Assert.Equal(10f, root_child1_child3.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Child_Multiline_Override()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(60f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(25f);
        root_child1.FlexWrap = FlexWrap.Wrap;
        root_child1.FlexDirection = FlexDirection.Row;
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(25f);
        root_child1_child0.Height = YogaValue.Point(20f);
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child1_child1 = new YogaNode(config);
        root_child1_child1.Width = YogaValue.Point(25f);
        root_child1_child1.Height = YogaValue.Point(10f);
        root_child1_child1.AlignSelf = FlexAlign.Baseline;
        root_child1.InsertChild(root_child1_child1, 1);
        var root_child1_child2 = new YogaNode(config);
        root_child1_child2.Width = YogaValue.Point(25f);
        root_child1_child2.Height = YogaValue.Point(20f);
        root_child1.InsertChild(root_child1_child2, 2);
        var root_child1_child3 = new YogaNode(config);
        root_child1_child3.Width = YogaValue.Point(25f);
        root_child1_child3.Height = YogaValue.Point(10f);
        root_child1_child3.AlignSelf = FlexAlign.Baseline;
        root_child1.InsertChild(root_child1_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(60f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(50f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(25f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(25f, root_child1_child1.LayoutX);
        Assert.Equal(0f, root_child1_child1.LayoutY);
        Assert.Equal(25f, root_child1_child1.LayoutWidth);
        Assert.Equal(10f, root_child1_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child2.LayoutX);
        Assert.Equal(20f, root_child1_child2.LayoutY);
        Assert.Equal(25f, root_child1_child2.LayoutWidth);
        Assert.Equal(20f, root_child1_child2.LayoutHeight);
        Assert.Equal(25f, root_child1_child3.LayoutX);
        Assert.Equal(20f, root_child1_child3.LayoutY);
        Assert.Equal(25f, root_child1_child3.LayoutWidth);
        Assert.Equal(10f, root_child1_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(60f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(50f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(25f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(25f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child1_child1.LayoutX);
        Assert.Equal(0f, root_child1_child1.LayoutY);
        Assert.Equal(25f, root_child1_child1.LayoutWidth);
        Assert.Equal(10f, root_child1_child1.LayoutHeight);
        Assert.Equal(25f, root_child1_child2.LayoutX);
        Assert.Equal(20f, root_child1_child2.LayoutY);
        Assert.Equal(25f, root_child1_child2.LayoutWidth);
        Assert.Equal(20f, root_child1_child2.LayoutHeight);
        Assert.Equal(0f, root_child1_child3.LayoutX);
        Assert.Equal(20f, root_child1_child3.LayoutY);
        Assert.Equal(25f, root_child1_child3.LayoutWidth);
        Assert.Equal(10f, root_child1_child3.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Child_Multiline_No_Override_On_Secondline()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(60f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(25f);
        root_child1.FlexWrap = FlexWrap.Wrap;
        root_child1.FlexDirection = FlexDirection.Row;
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(25f);
        root_child1_child0.Height = YogaValue.Point(20f);
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child1_child1 = new YogaNode(config);
        root_child1_child1.Width = YogaValue.Point(25f);
        root_child1_child1.Height = YogaValue.Point(10f);
        root_child1.InsertChild(root_child1_child1, 1);
        var root_child1_child2 = new YogaNode(config);
        root_child1_child2.Width = YogaValue.Point(25f);
        root_child1_child2.Height = YogaValue.Point(20f);
        root_child1.InsertChild(root_child1_child2, 2);
        var root_child1_child3 = new YogaNode(config);
        root_child1_child3.Width = YogaValue.Point(25f);
        root_child1_child3.Height = YogaValue.Point(10f);
        root_child1_child3.AlignSelf = FlexAlign.Baseline;
        root_child1.InsertChild(root_child1_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(60f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(25f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(25f, root_child1_child1.LayoutX);
        Assert.Equal(0f, root_child1_child1.LayoutY);
        Assert.Equal(25f, root_child1_child1.LayoutWidth);
        Assert.Equal(10f, root_child1_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child2.LayoutX);
        Assert.Equal(20f, root_child1_child2.LayoutY);
        Assert.Equal(25f, root_child1_child2.LayoutWidth);
        Assert.Equal(20f, root_child1_child2.LayoutHeight);
        Assert.Equal(25f, root_child1_child3.LayoutX);
        Assert.Equal(20f, root_child1_child3.LayoutY);
        Assert.Equal(25f, root_child1_child3.LayoutWidth);
        Assert.Equal(10f, root_child1_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(60f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(25f, root_child1.LayoutHeight);
        Assert.Equal(25f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(25f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child1_child1.LayoutX);
        Assert.Equal(0f, root_child1_child1.LayoutY);
        Assert.Equal(25f, root_child1_child1.LayoutWidth);
        Assert.Equal(10f, root_child1_child1.LayoutHeight);
        Assert.Equal(25f, root_child1_child2.LayoutX);
        Assert.Equal(20f, root_child1_child2.LayoutY);
        Assert.Equal(25f, root_child1_child2.LayoutWidth);
        Assert.Equal(20f, root_child1_child2.LayoutHeight);
        Assert.Equal(0f, root_child1_child3.LayoutX);
        Assert.Equal(20f, root_child1_child3.LayoutY);
        Assert.Equal(25f, root_child1_child3.LayoutWidth);
        Assert.Equal(10f, root_child1_child3.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Child_Top()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root_child0.SetPosition(YogaEdge.Top, YogaValue.Point(10f));
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(20f);
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(50f);
        root_child1_child0.Height = YogaValue.Point(10f);
        root_child1.InsertChild(root_child1_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(10f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(10f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Child_Top2()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.SetPosition(YogaEdge.Top, YogaValue.Point(5f));
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(50f);
        root_child1_child0.Height = YogaValue.Point(10f);
        root_child1.InsertChild(root_child1_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(45f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(45f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Double_Nested_Child()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.Width = YogaValue.Point(50f);
        root_child0_child0.Height = YogaValue.Point(20f);
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(20f);
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(50f);
        root_child1_child0.Height = YogaValue.Point(15f);
        root_child1.InsertChild(root_child1_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(50f, root_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(5f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(15f, root_child1_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(50f, root_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(5f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(15f, root_child1_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Column()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(20f);
        root.InsertChild(root_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(50f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(50f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Child_Margin()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root_child0.SetMargin(YogaEdge.All, YogaValue.Point(5f));
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(20f);
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(50f);
        root_child1_child0.Height = YogaValue.Point(10f);
        root_child1_child0.SetMargin(YogaEdge.All, YogaValue.Point(1f));
        root_child1.InsertChild(root_child1_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(5f, root_child0.LayoutX);
        Assert.Equal(5f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(60f, root_child1.LayoutX);
        Assert.Equal(44f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(1f, root_child1_child0.LayoutX);
        Assert.Equal(1f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(45f, root_child0.LayoutX);
        Assert.Equal(5f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(-10f, root_child1.LayoutX);
        Assert.Equal(44f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(-1f, root_child1_child0.LayoutX);
        Assert.Equal(1f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Child_Padding()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.SetPadding(YogaEdge.All, YogaValue.Point(5f));
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.SetPadding(YogaEdge.All, YogaValue.Point(5f));
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(50f);
        root_child1_child0.Height = YogaValue.Point(10f);
        root_child1.InsertChild(root_child1_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(5f, root_child0.LayoutX);
        Assert.Equal(5f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(55f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(5f, root_child1_child0.LayoutX);
        Assert.Equal(5f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(45f, root_child0.LayoutX);
        Assert.Equal(5f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(-5f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(-5f, root_child1_child0.LayoutX);
        Assert.Equal(5f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Multiline()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(20f);
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(50f);
        root_child1_child0.Height = YogaValue.Point(10f);
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child2 = new YogaNode(config);
        root_child2.Width = YogaValue.Point(50f);
        root_child2.Height = YogaValue.Point(20f);
        root.InsertChild(root_child2, 2);
        var root_child2_child0 = new YogaNode(config);
        root_child2_child0.Width = YogaValue.Point(50f);
        root_child2_child0.Height = YogaValue.Point(10f);
        root_child2.InsertChild(root_child2_child0, 0);
        var root_child3 = new YogaNode(config);
        root_child3.Width = YogaValue.Point(50f);
        root_child3.Height = YogaValue.Point(50f);
        root.InsertChild(root_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(100f, root_child2.LayoutY);
        Assert.Equal(50f, root_child2.LayoutWidth);
        Assert.Equal(20f, root_child2.LayoutHeight);
        Assert.Equal(0f, root_child2_child0.LayoutX);
        Assert.Equal(0f, root_child2_child0.LayoutY);
        Assert.Equal(50f, root_child2_child0.LayoutWidth);
        Assert.Equal(10f, root_child2_child0.LayoutHeight);
        Assert.Equal(50f, root_child3.LayoutX);
        Assert.Equal(60f, root_child3.LayoutY);
        Assert.Equal(50f, root_child3.LayoutWidth);
        Assert.Equal(50f, root_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(20f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        Assert.Equal(50f, root_child2.LayoutX);
        Assert.Equal(100f, root_child2.LayoutY);
        Assert.Equal(50f, root_child2.LayoutWidth);
        Assert.Equal(20f, root_child2.LayoutHeight);
        Assert.Equal(0f, root_child2_child0.LayoutX);
        Assert.Equal(0f, root_child2_child0.LayoutY);
        Assert.Equal(50f, root_child2_child0.LayoutWidth);
        Assert.Equal(10f, root_child2_child0.LayoutHeight);
        Assert.Equal(0f, root_child3.LayoutX);
        Assert.Equal(60f, root_child3.LayoutY);
        Assert.Equal(50f, root_child3.LayoutWidth);
        Assert.Equal(50f, root_child3.LayoutHeight);
    }

    [Fact(Skip = "Skipped in upstream Yoga (GTEST_SKIP)")]
    public void Align_Baseline_Multiline_Column()
    {
        // TODO: GTEST_SKIP();
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.AlignItems = FlexAlign.Baseline;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(30f);
        root_child1.Height = YogaValue.Point(50f);
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(20f);
        root_child1_child0.Height = YogaValue.Point(20f);
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child2 = new YogaNode(config);
        root_child2.Width = YogaValue.Point(40f);
        root_child2.Height = YogaValue.Point(70f);
        root.InsertChild(root_child2, 2);
        var root_child2_child0 = new YogaNode(config);
        root_child2_child0.Width = YogaValue.Point(10f);
        root_child2_child0.Height = YogaValue.Point(10f);
        root_child2.InsertChild(root_child2_child0, 0);
        var root_child3 = new YogaNode(config);
        root_child3.Width = YogaValue.Point(50f);
        root_child3.Height = YogaValue.Point(20f);
        root.InsertChild(root_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(50f, root_child1.LayoutY);
        Assert.Equal(30f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(20f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(50f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(40f, root_child2.LayoutWidth);
        Assert.Equal(70f, root_child2.LayoutHeight);
        Assert.Equal(0f, root_child2_child0.LayoutX);
        Assert.Equal(0f, root_child2_child0.LayoutY);
        Assert.Equal(10f, root_child2_child0.LayoutWidth);
        Assert.Equal(10f, root_child2_child0.LayoutHeight);
        Assert.Equal(50f, root_child3.LayoutX);
        Assert.Equal(70f, root_child3.LayoutY);
        Assert.Equal(50f, root_child3.LayoutWidth);
        Assert.Equal(20f, root_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(50f, root_child1.LayoutY);
        Assert.Equal(30f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
        Assert.Equal(10f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(20f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(40f, root_child2.LayoutWidth);
        Assert.Equal(70f, root_child2.LayoutHeight);
        Assert.Equal(30f, root_child2_child0.LayoutX);
        Assert.Equal(0f, root_child2_child0.LayoutY);
        Assert.Equal(10f, root_child2_child0.LayoutWidth);
        Assert.Equal(10f, root_child2_child0.LayoutHeight);
        Assert.Equal(0f, root_child3.LayoutX);
        Assert.Equal(70f, root_child3.LayoutY);
        Assert.Equal(50f, root_child3.LayoutWidth);
        Assert.Equal(20f, root_child3.LayoutHeight);
    }

    [Fact(Skip = "Skipped in upstream Yoga (GTEST_SKIP)")]
    public void Align_Baseline_Multiline_Column2()
    {
        // TODO: GTEST_SKIP();
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.AlignItems = FlexAlign.Baseline;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(30f);
        root_child1.Height = YogaValue.Point(50f);
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(20f);
        root_child1_child0.Height = YogaValue.Point(20f);
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child2 = new YogaNode(config);
        root_child2.Width = YogaValue.Point(40f);
        root_child2.Height = YogaValue.Point(70f);
        root.InsertChild(root_child2, 2);
        var root_child2_child0 = new YogaNode(config);
        root_child2_child0.Width = YogaValue.Point(10f);
        root_child2_child0.Height = YogaValue.Point(10f);
        root_child2.InsertChild(root_child2_child0, 0);
        var root_child3 = new YogaNode(config);
        root_child3.Width = YogaValue.Point(50f);
        root_child3.Height = YogaValue.Point(20f);
        root.InsertChild(root_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(50f, root_child1.LayoutY);
        Assert.Equal(30f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(20f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(50f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(40f, root_child2.LayoutWidth);
        Assert.Equal(70f, root_child2.LayoutHeight);
        Assert.Equal(0f, root_child2_child0.LayoutX);
        Assert.Equal(0f, root_child2_child0.LayoutY);
        Assert.Equal(10f, root_child2_child0.LayoutWidth);
        Assert.Equal(10f, root_child2_child0.LayoutHeight);
        Assert.Equal(50f, root_child3.LayoutX);
        Assert.Equal(70f, root_child3.LayoutY);
        Assert.Equal(50f, root_child3.LayoutWidth);
        Assert.Equal(20f, root_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(50f, root_child1.LayoutY);
        Assert.Equal(30f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
        Assert.Equal(10f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(20f, root_child1_child0.LayoutWidth);
        Assert.Equal(20f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(0f, root_child2.LayoutY);
        Assert.Equal(40f, root_child2.LayoutWidth);
        Assert.Equal(70f, root_child2.LayoutHeight);
        Assert.Equal(30f, root_child2_child0.LayoutX);
        Assert.Equal(0f, root_child2_child0.LayoutY);
        Assert.Equal(10f, root_child2_child0.LayoutWidth);
        Assert.Equal(10f, root_child2_child0.LayoutHeight);
        Assert.Equal(0f, root_child3.LayoutX);
        Assert.Equal(70f, root_child3.LayoutY);
        Assert.Equal(50f, root_child3.LayoutWidth);
        Assert.Equal(20f, root_child3.LayoutHeight);
    }

    [Fact]
    public void Align_Baseline_Multiline_Row_And_Column()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.AlignItems = FlexAlign.Baseline;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(50f);
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(50f);
        root_child1_child0.Height = YogaValue.Point(10f);
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child2 = new YogaNode(config);
        root_child2.Width = YogaValue.Point(50f);
        root_child2.Height = YogaValue.Point(20f);
        root.InsertChild(root_child2, 2);
        var root_child2_child0 = new YogaNode(config);
        root_child2_child0.Width = YogaValue.Point(50f);
        root_child2_child0.Height = YogaValue.Point(10f);
        root_child2.InsertChild(root_child2_child0, 0);
        var root_child3 = new YogaNode(config);
        root_child3.Width = YogaValue.Point(50f);
        root_child3.Height = YogaValue.Point(20f);
        root.InsertChild(root_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(50f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        Assert.Equal(0f, root_child2.LayoutX);
        Assert.Equal(100f, root_child2.LayoutY);
        Assert.Equal(50f, root_child2.LayoutWidth);
        Assert.Equal(20f, root_child2.LayoutHeight);
        Assert.Equal(0f, root_child2_child0.LayoutX);
        Assert.Equal(0f, root_child2_child0.LayoutY);
        Assert.Equal(50f, root_child2_child0.LayoutWidth);
        Assert.Equal(10f, root_child2_child0.LayoutHeight);
        Assert.Equal(50f, root_child3.LayoutX);
        Assert.Equal(90f, root_child3.LayoutY);
        Assert.Equal(50f, root_child3.LayoutWidth);
        Assert.Equal(20f, root_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(50f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child1.LayoutX);
        Assert.Equal(40f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
        Assert.Equal(0f, root_child1_child0.LayoutX);
        Assert.Equal(0f, root_child1_child0.LayoutY);
        Assert.Equal(50f, root_child1_child0.LayoutWidth);
        Assert.Equal(10f, root_child1_child0.LayoutHeight);
        Assert.Equal(50f, root_child2.LayoutX);
        Assert.Equal(100f, root_child2.LayoutY);
        Assert.Equal(50f, root_child2.LayoutWidth);
        Assert.Equal(20f, root_child2.LayoutHeight);
        Assert.Equal(0f, root_child2_child0.LayoutX);
        Assert.Equal(0f, root_child2_child0.LayoutY);
        Assert.Equal(50f, root_child2_child0.LayoutWidth);
        Assert.Equal(10f, root_child2_child0.LayoutHeight);
        Assert.Equal(0f, root_child3.LayoutX);
        Assert.Equal(90f, root_child3.LayoutY);
        Assert.Equal(50f, root_child3.LayoutWidth);
        Assert.Equal(20f, root_child3.LayoutHeight);
    }

    [Fact]
    public void Align_Items_Center_Child_With_Margin_Bigger_Than_Parent()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(52f);
        root.Width = YogaValue.Point(52f);
        root.AlignItems = FlexAlign.Center;
        root.JustifyContent = FlexJustify.Center;
        var root_child0 = new YogaNode(config);
        root_child0.AlignItems = FlexAlign.Center;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.Width = YogaValue.Point(52f);
        root_child0_child0.Height = YogaValue.Point(52f);
        root_child0_child0.SetMargin(YogaEdge.Left, YogaValue.Point(10f));
        root_child0_child0.SetMargin(YogaEdge.Right, YogaValue.Point(10f));
        root_child0.InsertChild(root_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(52f, root.LayoutWidth);
        Assert.Equal(52f, root.LayoutHeight);
        Assert.Equal(-10f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(72f, root_child0.LayoutWidth);
        Assert.Equal(52f, root_child0.LayoutHeight);
        Assert.Equal(10f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(52f, root_child0_child0.LayoutWidth);
        Assert.Equal(52f, root_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(52f, root.LayoutWidth);
        Assert.Equal(52f, root.LayoutHeight);
        Assert.Equal(-10f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(72f, root_child0.LayoutWidth);
        Assert.Equal(52f, root_child0.LayoutHeight);
        Assert.Equal(10f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(52f, root_child0_child0.LayoutWidth);
        Assert.Equal(52f, root_child0_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Items_Flex_End_Child_With_Margin_Bigger_Than_Parent()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(52f);
        root.Width = YogaValue.Point(52f);
        root.AlignItems = FlexAlign.Center;
        root.JustifyContent = FlexJustify.Center;
        var root_child0 = new YogaNode(config);
        root_child0.AlignItems = FlexAlign.FlexEnd;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.Width = YogaValue.Point(52f);
        root_child0_child0.Height = YogaValue.Point(52f);
        root_child0_child0.SetMargin(YogaEdge.Left, YogaValue.Point(10f));
        root_child0_child0.SetMargin(YogaEdge.Right, YogaValue.Point(10f));
        root_child0.InsertChild(root_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(52f, root.LayoutWidth);
        Assert.Equal(52f, root.LayoutHeight);
        Assert.Equal(-10f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(72f, root_child0.LayoutWidth);
        Assert.Equal(52f, root_child0.LayoutHeight);
        Assert.Equal(10f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(52f, root_child0_child0.LayoutWidth);
        Assert.Equal(52f, root_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(52f, root.LayoutWidth);
        Assert.Equal(52f, root.LayoutHeight);
        Assert.Equal(-10f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(72f, root_child0.LayoutWidth);
        Assert.Equal(52f, root_child0.LayoutHeight);
        Assert.Equal(10f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(52f, root_child0_child0.LayoutWidth);
        Assert.Equal(52f, root_child0_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Items_Center_Child_Without_Margin_Bigger_Than_Parent()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(52f);
        root.Width = YogaValue.Point(52f);
        root.AlignItems = FlexAlign.Center;
        root.JustifyContent = FlexJustify.Center;
        var root_child0 = new YogaNode(config);
        root_child0.AlignItems = FlexAlign.Center;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.Width = YogaValue.Point(72f);
        root_child0_child0.Height = YogaValue.Point(72f);
        root_child0.InsertChild(root_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(52f, root.LayoutWidth);
        Assert.Equal(52f, root.LayoutHeight);
        Assert.Equal(-10f, root_child0.LayoutX);
        Assert.Equal(-10f, root_child0.LayoutY);
        Assert.Equal(72f, root_child0.LayoutWidth);
        Assert.Equal(72f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(72f, root_child0_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(52f, root.LayoutWidth);
        Assert.Equal(52f, root.LayoutHeight);
        Assert.Equal(-10f, root_child0.LayoutX);
        Assert.Equal(-10f, root_child0.LayoutY);
        Assert.Equal(72f, root_child0.LayoutWidth);
        Assert.Equal(72f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(72f, root_child0_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Items_Flex_End_Child_Without_Margin_Bigger_Than_Parent()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(52f);
        root.Width = YogaValue.Point(52f);
        root.AlignItems = FlexAlign.Center;
        root.JustifyContent = FlexJustify.Center;
        var root_child0 = new YogaNode(config);
        root_child0.AlignItems = FlexAlign.FlexEnd;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.Width = YogaValue.Point(72f);
        root_child0_child0.Height = YogaValue.Point(72f);
        root_child0.InsertChild(root_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(52f, root.LayoutWidth);
        Assert.Equal(52f, root.LayoutHeight);
        Assert.Equal(-10f, root_child0.LayoutX);
        Assert.Equal(-10f, root_child0.LayoutY);
        Assert.Equal(72f, root_child0.LayoutWidth);
        Assert.Equal(72f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(72f, root_child0_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(52f, root.LayoutWidth);
        Assert.Equal(52f, root.LayoutHeight);
        Assert.Equal(-10f, root_child0.LayoutX);
        Assert.Equal(-10f, root_child0.LayoutY);
        Assert.Equal(72f, root_child0.LayoutWidth);
        Assert.Equal(72f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(72f, root_child0_child0.LayoutWidth);
        Assert.Equal(72f, root_child0_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Center_Should_Size_Based_On_Content()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.AlignItems = FlexAlign.Center;
        root.SetMargin(YogaEdge.Top, YogaValue.Point(20f));
        var root_child0 = new YogaNode(config);
        root_child0.FlexShrink = 1f;
        root_child0.JustifyContent = FlexJustify.Center;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.FlexGrow = 1f;
        root_child0_child0.FlexShrink = 1f;
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.Width = YogaValue.Point(20f);
        root_child0_child0_child0.Height = YogaValue.Point(20f);
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(20f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(40f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(20f, root_child0.LayoutWidth);
        Assert.Equal(20f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(20f, root_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(20f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(20f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(40f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(20f, root_child0.LayoutWidth);
        Assert.Equal(20f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(20f, root_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(20f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Stretch_Should_Size_Based_On_Parent()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.SetMargin(YogaEdge.Top, YogaValue.Point(20f));
        var root_child0 = new YogaNode(config);
        root_child0.FlexShrink = 1f;
        root_child0.JustifyContent = FlexJustify.Center;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.FlexGrow = 1f;
        root_child0_child0.FlexShrink = 1f;
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.Width = YogaValue.Point(20f);
        root_child0_child0_child0.Height = YogaValue.Point(20f);
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(20f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(20f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(100f, root_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(20f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(20f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(100f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(100f, root_child0.LayoutWidth);
        Assert.Equal(20f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(100f, root_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0.LayoutHeight);
        Assert.Equal(80f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(20f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(20f, root_child0_child0_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Flex_Start_With_Shrinking_Children()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(500f);
        root.Width = YogaValue.Point(500f);
        var root_child0 = new YogaNode(config);
        root_child0.AlignItems = FlexAlign.FlexStart;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.FlexGrow = 1f;
        root_child0_child0.FlexShrink = 1f;
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.FlexGrow = 1f;
        root_child0_child0_child0.FlexShrink = 1f;
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(500f, root.LayoutWidth);
        Assert.Equal(500f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(500f, root_child0.LayoutWidth);
        Assert.Equal(0f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(500f, root.LayoutWidth);
        Assert.Equal(500f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(500f, root_child0.LayoutWidth);
        Assert.Equal(0f, root_child0.LayoutHeight);
        Assert.Equal(500f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Flex_Start_With_Stretching_Children()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(500f);
        root.Width = YogaValue.Point(500f);
        var root_child0 = new YogaNode(config);
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.FlexGrow = 1f;
        root_child0_child0.FlexShrink = 1f;
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.FlexGrow = 1f;
        root_child0_child0_child0.FlexShrink = 1f;
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(500f, root.LayoutWidth);
        Assert.Equal(500f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(500f, root_child0.LayoutWidth);
        Assert.Equal(0f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(500f, root_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(500f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(500f, root.LayoutWidth);
        Assert.Equal(500f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(500f, root_child0.LayoutWidth);
        Assert.Equal(0f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(500f, root_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(500f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Flex_Start_With_Shrinking_Children_With_Stretch()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(500f);
        root.Width = YogaValue.Point(500f);
        var root_child0 = new YogaNode(config);
        root_child0.AlignItems = FlexAlign.FlexStart;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.FlexGrow = 1f;
        root_child0_child0.FlexShrink = 1f;
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.FlexGrow = 1f;
        root_child0_child0_child0.FlexShrink = 1f;
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(500f, root.LayoutWidth);
        Assert.Equal(500f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(500f, root_child0.LayoutWidth);
        Assert.Equal(0f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(500f, root.LayoutWidth);
        Assert.Equal(500f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(500f, root_child0.LayoutWidth);
        Assert.Equal(0f, root_child0.LayoutHeight);
        Assert.Equal(500f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(0f, root_child0_child0_child0.LayoutHeight);
    }

    [Fact]
    public void Align_Flex_End_With_Row_Reverse()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(75f);
        root.AlignItems = FlexAlign.FlexEnd;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root_child0.SetMargin(YogaEdge.Right, YogaValue.Point(5f));
        root_child0.SetMargin(YogaEdge.Left, YogaValue.Point(3f));
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(50f);
        root.InsertChild(root_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(75f, root.LayoutHeight);
        Assert.Equal(3f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(58f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(75f, root.LayoutHeight);
        Assert.Equal(45f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(-8f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
    }

    [Fact]
    public void Align_Stretch_With_Row_Reverse()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(75f);
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root_child0.SetMargin(YogaEdge.Right, YogaValue.Point(5f));
        root_child0.SetMargin(YogaEdge.Left, YogaValue.Point(3f));
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(50f);
        root.InsertChild(root_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(75f, root.LayoutHeight);
        Assert.Equal(3f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(58f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(100f, root.LayoutWidth);
        Assert.Equal(75f, root.LayoutHeight);
        Assert.Equal(45f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(50f, root_child0.LayoutWidth);
        Assert.Equal(50f, root_child0.LayoutHeight);
        Assert.Equal(-8f, root_child1.LayoutX);
        Assert.Equal(0f, root_child1.LayoutY);
        Assert.Equal(50f, root_child1.LayoutWidth);
        Assert.Equal(50f, root_child1.LayoutHeight);
    }

    [Fact]
    public void Align_Items_Non_Stretch_S526008()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(400f);
        root.Height = YogaValue.Point(400f);
        var root_child0 = new YogaNode(config);
        root_child0.FlexDirection = FlexDirection.Row;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.AlignItems = FlexAlign.FlexStart;
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        var root_child0_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0_child0.Width = YogaValue.Point(0f);
        root_child0_child0_child0_child0.Height = YogaValue.Point(10f);
        root_child0_child0_child0.InsertChild(root_child0_child0_child0_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LTR);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(400f, root.LayoutWidth);
        Assert.Equal(400f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(400f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0.LayoutWidth);
        Assert.Equal(10f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(10f, root_child0_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0_child0.LayoutWidth);
        Assert.Equal(10f, root_child0_child0_child0_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RTL);
        Assert.Equal(0f, root.LayoutX);
        Assert.Equal(0f, root.LayoutY);
        Assert.Equal(400f, root.LayoutWidth);
        Assert.Equal(400f, root.LayoutHeight);
        Assert.Equal(0f, root_child0.LayoutX);
        Assert.Equal(0f, root_child0.LayoutY);
        Assert.Equal(400f, root_child0.LayoutWidth);
        Assert.Equal(10f, root_child0.LayoutHeight);
        Assert.Equal(400f, root_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0.LayoutWidth);
        Assert.Equal(10f, root_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0.LayoutWidth);
        Assert.Equal(10f, root_child0_child0_child0.LayoutHeight);
        Assert.Equal(0f, root_child0_child0_child0_child0.LayoutX);
        Assert.Equal(0f, root_child0_child0_child0_child0.LayoutY);
        Assert.Equal(0f, root_child0_child0_child0_child0.LayoutWidth);
        Assert.Equal(10f, root_child0_child0_child0_child0.LayoutHeight);
    }

}