name: CI - DevFlow

on:
  push:
    branches: [main]
    paths:
      - 'src/DevFlow/**'
      - 'eng/**'
      - 'Directory.Build.props'
      - 'Directory.Build.targets'
      - 'Directory.Packages.props'
      - 'global.json'
      - 'NuGet.config'
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
    paths:
      - 'src/DevFlow/**'
      - 'eng/**'
      - 'Directory.Build.props'
      - 'Directory.Build.targets'
      - 'Directory.Packages.props'
      - 'global.json'
      - 'NuGet.config'

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      project-path: src/DevFlow/DevFlow.slnf
      project-name: devflow
      run-tests: true
      pack: true
